# Welcome to Impatient-Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically.

# Site settings
title: Diccionario del cliché
excerpt: Un proyecto de innovación docente coordinado por José Alberto García Avilés y desarrollado por Miguel Carvajal para el Máster en Innovación en Periodismo y el Grado en Periodismo UMH
baseurl: "" # the subpath of your site, e.g. /blog
email: diccionariodelcliche@gmail.com
# Build settings
markdown: kramdown

# Postal address (add as many lines as necessary)
collections:
  cliches:
    output: true

# Setup
include: ["_pages"]
permalink: /:title/

# Sass converter configuration
sass:
    sass_dir: _sass
    style: compressed

# Local Server
host: localhost # same as default value '127.0.0.1' but reads better

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .sass-cache
  - .netlify
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
